### ISSUE TITLE
How to change the default encoding setting "US-ASCII" to "UTF-8" when selecting build system with "Python + Virtualenv" ?

### ISSUE THREAD

**Issue by ZWANG1212** [AdrianLC/sublime-text-virtualenv#15]
import sys
print("sys.stdout.encoding", sys.stdout.encoding) 

RESULT: sys.stdout.encoding US-ASCII

I have tried adding "env": {"LANG": "en_US.UTF-8"}, in the Virtualenv.sublime-settings, but it didn't work.

**Comment by abelikoff** [comment]
You can set it via environment variable:

`export PYTHONIOENCODING=utf8`
