### ISSUE TITLE
Can't find egg-linked development module

### ISSUE THREAD

**Issue by rmx90210** [AdrianLC/sublime-text-virtualenv#2]
I'm developing a Python package (in Windows) which is linked to my global site-packages with the usual `setup.py develop`. When I activate the virtualenv using the plugin and try to `import mymodule` I get an `ImportError`. Other locally installed packages (i.e. not egg-linked) work fine.

I thought this might be an issue with my virtualenv, but if I activate it from a command prompt and open a Python shell I can import my module without any issues. It seems like there's an problem with Sublime not recognizing egg-linked modules -- is there some workaround for this?

Many thanks

**Comment by AdrianLC** [comment]
Hi. Were you finally able to make it work?

**Comment by rmx90210** [comment]
Hi Adrian, yes I was. I just had to put `python` in front of `setup.py develop`. Oh Windows...
